### ISSUE TITLE
Can't validate any XLIFF file

### ISSUE THREAD

**Issue by andreasciamanna** [rmraya/XLIFFManager#1]
I've tried to find a solution on my own and then searched here where I see no open or closed issues, so I wonder if that's the right place where to ask.

I can't validate any XLIFF file.

Clicking the "Browse" button, all files are greyed out, including the XLIFF ones:

![image](https://user-images.githubusercontent.com/181780/51603214-691a2a80-1f09-11e9-8c93-7b164c5c3394.png)

In case that's not obvious, I'm on a Mac :)

Manually entering the full path of the file (can't use the clipboard either) works.

Thanks!

**Comment by rmraya** [comment]
Your files have wrong extension. Change them from .xliff to .xlf.

The XLIFF standard says that ".xlf" is the extension to use for XLIFF files.

Just by having a wrong extension your files are not valid!

**Comment by andreasciamanna** [comment]
Thanks for the quick answer!
