### ISSUE TITLE
'Merge XLIFF' does not save as .xlf

### ISSUE THREAD

**Issue by davidarndtsick** [rmraya/XLIFFManager#7]
When using the 'Merge XLIFF' function, the target file currently does not automatically receive the .xlf file extension.
This is in contrast to the 'Create XLIFF' function, where the file extension is added, even, if it's already present.

Can you have the Merge function also add .xlf automatically? this will save some time each use.

Thanks & best regards,
David

**Comment by rmraya** [comment]
Merge adds the extension of the source file automatically. If the source file was an XLIFF file with `.xlf` extension, that extension should be automatically preserved. If that does not happen, please attach a test case.

**Comment by davidarndtsick** [comment]
Hi, unfortunately, that doesn't see to be the case. 

Here are the steps I'm taking with the resulting filename.
Step 1: Export XLIFF from Articulate Rise --> Translation.xlf
Step 2: 'Create XLIFF' to convert it from v1.2 to 2.1 --> Translation.xlf.xlf
Step 3: Translate it through DeepL --> Translationtest.xlf_0_translated_DE.xlf
Step 4: 'Merge XLIFF' --> Translationtest_de.xlf_0_translated_DE

Attached all XLIFF files from the process:
[Translationtest-filenaming.zip](https://github.com/user-attachments/files/16085858/Translationtest-filenaming.zip)

Best Regards,
David

**Comment by rmraya** [comment]
Thank you for the test case.

**Comment by rmraya** [comment]
The file you get at step 3 does not have the right extension. Its name should end in `.xlf.xlf`.
You may get the desired result if the name of the file you merge in step 4 is `Translationtest_0_translated_DE.xlf.xlf` instead.
Note that you can change the name of the target file when merging.
